type Recipe {
  id: ID!
  title: String!
  author: String!
  ingredients: [String!]!
  steps: [String!]!
}

input CreateRecipeInput {
  title: String!
  author: String!
  ingredients: [String!]!
  steps: [String!]!
}

type Query {
  recipe(id: ID!): Recipe
  recipes: [Recipe]!
}

type Mutation {
  createRecipe(input: CreateRecipeInput!): Recipe!
}
